export const categories = [
    {
        category: "Ink",
        products: [
            {
                slug: "kpl-blue-7000-d",
                name: "KPL Blue 7000 D",
                desc: "General redder grade with 10% pigment loading",
                tags: ["PB 15.0", "Ink"],
                application: ["W.B Ink"],
                shades: ["#18193C", "#4464BA"],
                msds: `/product/MSDS/1_MSDS LIiquid Ink all products/MSDS KPL Blue 7000 D.pdf`,
                tds: `/product/TDS/TDS Liquid Ink All Grades.xls`,
                category: "Ink",
                use: ["Suitable", "Potential use"],
                meta: {
                    title: "KPL Blue 7000 D – Kesar Petroproducts Ltd. | Ink Product",
                    description:
                        "KPL Blue 7000 D is a general redder grade ink with 10% pigment loading, suitable for W.B Ink applications.",
                    keywords: "KPL Blue 7000 D, PB 15.0, Ink, W.B Ink, Kesar Petroproducts",
                    author: "Kesar Petroproducts Ltd.",
                    robots: "index,follow",
                },
            },
            {
                slug: "kpl-blue-7003-d",
                name: "KPL Blue 7003 D",
                desc: "General redder grade with 10% pigment loading",
                tags: ["PB 15.3", "INK"],
                application: ["NC - PU", "NC Alcohol", "PA", "Vinyl - EVA"],
                shades: ["#2C2681", "#3995D0"],
                msds: `/product/MSDS/1_MSDS LIiquid Ink all products/MSDS KPL Blue 7003 D.pdf`,
                tds: `/product/TDS/TDS Liquid Ink All Grades.xls`,
                category: "Ink",
                use: ["Suitable", "Potential use"],
                meta: {
                    title: "KPL Blue 7003 D – Kesar Petroproducts Ltd. | Ink Product",
                    description:
                        "KPL Blue 7003 D is a general redder grade ink with 10% pigment loading, suitable for NC - PU, NC Alcohol, PA, and Vinyl - EVA applications.",
                    keywords: "KPL Blue 7003 D, PB 15.3, Ink, NC - PU, NC Alcohol, PA, Vinyl - EVA, Kesar Petroproducts",
                    author: "Kesar Petroproducts Ltd.",
                    robots: "index,follow",
                },
            },
            {
                slug: "kpl-blue-7003-wd",
                name: "KPL Blue 7003 WD",
                desc: "Higher pigment loading (40-45%) with good gloss, transparency and viscosity",
                tags: ["PB 15.3", "Ink"],
                application: ["W.B Ink"],
                shades: ["#2C3AA4", "#3565B9"],
                msds: `/product/MSDS/1_MSDS LIiquid Ink all products/MSDS KPL Blue 7003 WD.pdf`,
                tds: `/product/TDS/TDS Liquid Ink All Grades.xls`,
                category: "Ink",
                use: ["Suitable", "Potential use"],
                meta: {
                    title: "KPL Blue 7003 WD – Kesar Petroproducts Ltd. | Ink Product",
                    description:
                        "KPL Blue 7003 WD is a high pigment loading (40-45%) ink with excellent gloss, transparency, and viscosity, suitable for W.B Ink applications.",
                    keywords: "KPL Blue 7003 WD, PB 15.3, Ink, W.B Ink, high pigment ink, Kesar Petroproducts",
                    author: "Kesar Petroproducts Ltd.",
                    robots: "index,follow",
                },
            },
            {
                slug: "kp-green-9000-d",
                name: "KP Green 9000 D",
                desc: "Good gloss, transparency and flow",
                tags: ["PG 7", "Ink"],
                application: ["W.B Ink", "NC - PU", "NC - Alcohol", "PA", "Vinyl - EVA"],
                shades: ["#00681F", "#5BDE69"],
                msds: `/product/MSDS/1_MSDS LIiquid Ink all products/MSDS KPL Green 9000 D.pdf`,
                tds: `/product/TDS/TDS Liquid Ink All Grades.xls`,
                category: "Ink",
                use: ["Suitable", "Potential use"],
                meta: {
                    title: "KP Green 9000 D – Kesar Petroproducts Ltd. | Ink Product",
                    description:
                        "KP Green 9000 D ink offers good gloss, transparency, and flow. Suitable for W.B Ink, NC - PU, NC - Alcohol, PA, and Vinyl - EVA applications.",
                    keywords: "KP Green 9000 D, PG 7, Ink, W.B Ink, NC - PU, NC - Alcohol, PA, Vinyl - EVA, Kesar Petroproducts",
                    author: "Kesar Petroproducts Ltd.",
                    robots: "index,follow",
                },
            },
        ]
    },
    {
        category: "Coating",
        products: [
            {
                slug: "kpl-blue-7000-wl",
                name: "KPL Blue 7000 WL",
                desc: "Specially using for water based emulsion paint system",
                tags: ["PB 15.0", "Coating"],
                decorative: ["Water Based"],
                Properties: ["Light Fastness Full Tone / RT: 8/8", "Weather Fastness Full Tone / RT: 5/5", "Heat Stability (°C): 160", "Overspray: 5/5"],
                shades: ["#18193C", "#4464BA"],
                msds: `/product/MSDS/2_MSDS Coating All Grades/MSDS KPL Blue 7000WL.pdf`,
                tds: `/product/TDS/TDS Coating All Grades.xlsx`,
                category: "Coating",
                use: ["Suitable", "Potential use"],
                meta: {
                    title: "KPL Blue 7000 WL – Kesar Petroproducts Ltd. | Water Based Coating",
                    description: "KPL Blue 7000 WL is specially designed for water based emulsion paint systems, providing excellent light fastness and weather resistance.",
                    keywords: "KPL Blue 7000 WL, PB 15.0, Water Based Coating, Kesar Petroproducts",
                    author: "Kesar Petroproducts Ltd.",
                    robots: "index,follow",
                },
            },
            {
                slug: "kpl-blue-7000-tx",
                name: "KPL Blue 7000 Tx",
                desc: "Specially using for textile emulsion system",
                tags: ["PB 15.0", "Coating"],
                decorative: ["Water Based", "Textile Emulsion"],
                Properties: ["Light Fastness Full Tone / RT: 8/8", "Weather Fastness Full Tone / RT: 5/5", "Heat Stability (°C): 160", "Overspray: 5/5"],
                shades: ["#2640A5", "#2640A5"],
                msds: `/product/MSDS/2_MSDS Coating All Grades/MSDS KPL Blue 7000TX.pdf`,
                tds: `/product/TDS/TDS Coating All Grades.xlsx`,
                category: "Coating",
                use: ["Suitable", "Potential use"],
                meta: {
                    title: "KPL Blue 7000 Tx – Kesar Petroproducts Ltd. | Textile Emulsion Coating",
                    description: "KPL Blue 7000 Tx is specially formulated for textile emulsion systems, offering excellent light fastness, weather resistance, and heat stability.",
                    keywords: "KPL Blue 7000 Tx, PB 15.0, Textile Emulsion Coating, Kesar Petroproducts",
                    author: "Kesar Petroproducts Ltd.",
                    robots: "index,follow",
                },

            },
            {
                slug: "kpl-blue-7000-dd",
                name: "KPL Blue 7000 DD",
                desc: "Specially using for dry distemper with good dispersion and colour strength",
                tags: ["PB 15.0", "Coating"],
                decorative: ["Water Based", "Textile Emulsion", "Dry Distemper"],
                Properties: ["Light Fastness Full Tone / RT: 8/8", "Weather Fastness Full Tone / RT: 5/5", "Heat Stability (°C): 160", "Overspray: 5/5"],
                shades: ["#2640A5", "#2640A5"],
                msds: `/product/MSDS/2_MSDS Coating All Grades/MSDS KPL Blue 7000 DD.pdf`,
                tds: `/product/TDS/TDS Coating All Grades.xlsx`,
                category: "Coating",
                use: ["Suitable", "Potential use"],
                meta: {
                    title: "KPL Blue 7000 DD – Kesar Petroproducts Ltd. | Dry Distemper Coating",
                    description: "KPL Blue 7000 DD is ideal for dry distemper applications, providing excellent dispersion, color strength, and light fastness.",
                    keywords: "KPL Blue 7000 DD, PB 15.0, Dry Distemper Coating, Kesar Petroproducts",
                    author: "Kesar Petroproducts Ltd.",
                    robots: "index,follow",
                },

            },
            {
                slug: "kpl-blue-7001-l",
                name: "KPL Blue 7001 L",
                desc: "Suitable for universal stainer system",
                tags: ["PB 15.1", "Coating"],
                decorative: ["Solvent Based", "Water Based", "Textile Emulsion"],
                industrial: ["Automobile OEM", "Automobile Refinish", "Industrial Paint", "Powder Coating", "Coil Coating"],
                Properties: ["Light Fastness Full Tone / RT: 8/8", "Weather Fastness Full Tone / RT: 5/5", "Heat Stability (°C): 260", "Overspray: 5/5"],
                shades: ["#18193C", "#2640A5"],
                msds: `/product/MSDS/2_MSDS Coating All Grades/MSDS KPL Blue 7001L.pdf`,
                tds: `/product/TDS/TDS Coating All Grades.xlsx`,
                category: "Coating",
                use: ["Suitable", "Potential use"],
                meta: {
                    title: "KPL Blue 7001 L – Kesar Petroproducts Ltd. | Universal Stainer Coating",
                    description: "KPL Blue 7001 L is suitable for universal stainer systems, compatible with solvent and water based coatings, and various industrial applications.",
                    keywords: "KPL Blue 7001 L, PB 15.1, Universal Stainer Coating, Kesar Petroproducts",
                    author: "Kesar Petroproducts Ltd.",
                    robots: "index,follow",
                },

            },
            {
                slug: "kpl-blue-7003-l",
                name: "KPL Blue 7003 L",
                desc: "Suitable for universal stainer system",
                tags: ["PB 15.3", "Coating"],
                decorative: ["Solvent Based", "Water Based", "Textile Emulsion"],
                industrial: ["Automobile Refinish", "Powder Coating"],
                Properties: ["Light Fastness Full Tone / RT: 8/8", "Weather Fastness Full Tone / RT: 5/5", "Heat Stability (°C): 260", "Overspray: 5/5"],
                shades: ["#2C2681", "#3565B9"],
                msds: `/product/MSDS/2_MSDS Coating All Grades/MSDS KPL Blue 7003L.pdf`,
                tds: `/product/TDS/TDS Coating All Grades.xlsx`,
                category: "Coating",
                use: ["Suitable", "Potential use"],
                meta: {
                    title: "KPL Blue 7003 L – Kesar Petroproducts Ltd. | Universal Stainer Coating",
                    description: "KPL Blue 7003 L is suitable for universal stainer systems, ideal for solvent and water based coatings, and select industrial applications.",
                    keywords: "KPL Blue 7003 L, PB 15.3, Universal Stainer Coating, Kesar Petroproducts",
                    author: "Kesar Petroproducts Ltd.",
                    robots: "index,follow",
                },

            },
            {
                slug: "kpl-blue-7003-tx",
                name: "KPL Blue 7003 Tx",
                desc: "Specially using for textile emulsion system with bright, greener shade",
                tags: ["PB 15.3", "Coating"],
                decorative: ["Water Based", "Textile Emulsion"],
                Properties: ["Light Fastness Full Tone / RT: 8/8", "Weather Fastness Full Tone / RT: 5/5", "Heat Stability (°C): 260", "Overspray: 5/5"],
                shades: ["#2C2681", "#3565B9"],
                msds: `/product/MSDS/2_MSDS Coating All Grades/MSDS KPL Blue 7003TX.pdf`,
                tds: `/product/TDS/TDS Coating All Grades.xlsx`,
                category: "Coating",
                use: ["Suitable", "Potential use"],
                meta: {
                    title: "KPL Blue 7003 Tx – Kesar Petroproducts Ltd. | Textile Emulsion Coating",
                    description: "KPL Blue 7003 Tx is designed for textile emulsion systems, offering bright greener shades with excellent light and weather fastness.",
                    keywords: "KPL Blue 7003 Tx, PB 15.3, Textile Emulsion Coating, Kesar Petroproducts",
                    author: "Kesar Petroproducts Ltd.",
                    robots: "index,follow",
                },

            },
            {
                slug: "kpl-blue-7003-dd",
                name: "KPL Blue 7003 DD",
                desc: "Specially using for dry distemper with good dispersion and colour strength",
                tags: ["PB 15.3", "Coating"],
                decorative: ["Water Based", "Textile Emulsion", "Dry Distemper"],
                Properties: ["Light Fastness Full Tone / RT: 8/8", "Weather Fastness Full Tone / RT: 5/5", "Heat Stability (°C): 160", "Overspray: 5/5"],
                shades: ["#2C2681", "#3565B9"],
                msds: `/product/MSDS/2_MSDS Coating All Grades/MSDS KPL Blue 7003 DD.pdf`,
                tds: `/product/TDS/TDS Coating All Grades.xlsx`,
                category: "Coating",
                use: ["Suitable", "Potential use"],
                meta: {
                    title: "KPL Blue 7003 DD – Kesar Petroproducts Ltd. | Dry Distemper Coating",
                    description: "KPL Blue 7003 DD is ideal for dry distemper applications, providing excellent dispersion, colour strength, and light fastness.",
                    keywords: "KPL Blue 7003 DD, PB 15.3, Dry Distemper Coating, Kesar Petroproducts",
                    author: "Kesar Petroproducts Ltd.",
                    robots: "index,follow",
                },

            },
            {
                slug: "kpl-green-9000-u",
                name: "KPL Green 9000 U",
                desc: "Universal grade suitable for different types of coating system",
                tags: ["PG 7", "Coating"],
                decorative: ["Solvent Based", "Water Based", "Textile Emulsion", "Dry Distemper"],
                industrial: ["Automobile OEM", "Automobile Refinish", "Industrial Paint", "Powder Coating", "Coil Coating"],
                Properties: ["Light Fastness Full Tone / RT: 8/8", "Weather Fastness Full Tone / RT: 5/5", "Heat Stability (°C): 300", "Overspray: 5/5"],
                shades: ["#00A02C", "#5BDE69"],
                msds: `/product/MSDS/2_MSDS Coating All Grades/MSDS KPL Green 9000U.pdf`,
                tds: `/product/TDS/TDS Coating All Grades.xlsx`,
                category: "Coating",
                use: ["Suitable", "Potential use"],
                meta: {
                    title: "KPL Green 9000 U – Kesar Petroproducts Ltd. | Universal Coating",
                    description: "KPL Green 9000 U is a universal grade coating suitable for various coating systems, providing excellent light fastness, weather resistance, and heat stability.",
                    keywords: "KPL Green 9000 U, PG 7, Universal Coating, Kesar Petroproducts",
                    author: "Kesar Petroproducts Ltd.",
                    robots: "index,follow",
                },

            },
        ]
    },
    {
        category: "Plastic",
        products: [
            {
                slug: "kpl-blue-7000-k",
                name: "KPL Blue 7000 K",
                desc: "Good dispersion and color strength",
                tags: ["PB 15.0", "Plastic"],
                application: ["PVC & PVC Leather", "Rubber"],
                Properties: ["Light Fastness Full Tone / RT: 8/8", "Weather Fastness Full Tone / RT: 5/5", "Heat Stability in HDPE (°C): 160", "Bleeding in PVC - P: LOW"],
                shades: ["#18193C", "#4464BA"],
                msds: `/product/MSDS/3_MSDS Plastic All Grades/KPL Blue 7000 K.pdf`,
                tds: `/product/TDS/TDS KPL Blue 7000 K.pdf`,
                category: "Plastic",
                use: ["Suitable", "Potential use"],
                meta: {
                    title: "KPL Blue 7000 K – Kesar Petroproducts Ltd. | Plastic Pigment",
                    description: "KPL Blue 7000 K offers good dispersion and color strength, suitable for PVC, PVC Leather, and Rubber applications.",
                    keywords: "KPL Blue 7000 K, PB 15.0, Plastic Pigment, PVC, Rubber, Kesar Petroproducts",
                    author: "Kesar Petroproducts Ltd.",
                    robots: "index,follow",
                },
            },
            {
                slug: "kpl-blue-7001-ak",
                name: "KPL Blue 7001 AK",
                desc: "Good dispersion and color strength. Suitable for those inducer required lower heat stability",
                tags: ["PB 15.1", "Plastic"],
                application: ["Polyolefins", "PVC & PVC Leather", "PA / ABS", "PP Fiber", "Rubber"],
                Properties: ["Light Fastness Full Tone / RT: 8/8", "Weather Fastness Full Tone / RT: 5/5", "Heat Stability in HDPE (°C): 260", "Bleeding in PVC - P: 3"],
                shades: ["#18193C", "#2640A5"],
                msds: `/product/MSDS/3_MSDS Plastic All Grades/KPL Blue 7001 AK.pdf`,
                tds: `/product/TDS/TDS KPL Blue 7001 AK.pdf`,
                category: "Plastic",
                use: ["Suitable", "Potential use"],
                meta: {
                    title: "KPL Blue 7001 AK – Kesar Petroproducts Ltd. | Plastic Pigment",
                    description: "KPL Blue 7001 AK provides excellent dispersion and color strength, suitable for polyolefins, PVC, PA/ABS, PP Fiber, and Rubber applications.",
                    keywords: "KPL Blue 7001 AK, PB 15.1, Plastic Pigment, Polyolefins, PVC, Kesar Petroproducts",
                    author: "Kesar Petroproducts Ltd.",
                    robots: "index,follow",
                },
            },
            {
                slug: "kpl-blue-7001-bkfv",
                name: "KPL Blue 7001 BkFV",
                desc: "Good dispersion and color strength with heat stability of 280°C and good FPV",
                tags: ["PB 15.1", "Plastic"],
                application: ["Polyolefins", "PVC & PVC Leather", "PA / ABS", "Nylon 6", "PBT / PET", "PP Fiber"],
                Properties: ["Light Fastness Full Tone / RT: 8/8", "Weather Fastness Full Tone / RT: 5/5", "Heat Stability in HDPE (°C): 300", "Bleeding in PVC - P: 4"],
                shades: ["#18193C", "#2640A5"],
                msds: `/product/MSDS/3_MSDS Plastic All Grades/KPL Blue 7001 BKFV.pdf`,
                tds: `/product/TDS/TDS KPL Blue 7001 BKFV.pdf`,
                category: "Plastic",
                use: ["Suitable", "Potential use"],
                meta: {
                    title: "KPL Blue 7001 BkFV – Kesar Petroproducts Ltd. | Plastic Pigment",
                    description: "KPL Blue 7001 BkFV offers high heat stability (280°C) and good FPV, suitable for PVC, Nylon 6, PBT/PET, and other plastic applications.",
                    keywords: "KPL Blue 7001 BkFV, PB 15.1, Plastic Pigment, PVC, Nylon 6, Kesar Petroproducts",
                    author: "Kesar Petroproducts Ltd.",
                    robots: "index,follow",
                },
            },
            {
                slug: "kpl-blue-7001-ckfv",
                name: "KPL Blue 7001 CkFV",
                desc: "Good dispersion and color strength with heat stability of 300°C and good FPV value",
                tags: ["PB 15.1", "Plastic"],
                application: ["Polyolefins", "PVC & PVC Leather", "PA / ABS", "Nylon 6", "PBT / PET", "PP Fiber"],
                Properties: ["Light Fastness Full Tone / RT: 8/8", "Weather Fastness Full Tone / RT: 5/5", "Heat Stability in HDPE (°C): 300", "Bleeding in PVC - P: 4"],
                shades: ["#18193C", "#2640A5"],
                msds: `/product/MSDS/3_MSDS Plastic All Grades/KPL Blue 7001 CKFV.pdf`,
                tds: `/product/TDS/TDS KPL Blue 7001 CKFV.pdf`,
                category: "Plastic",
                use: ["Suitable", "Potential use"],
                meta: {
                    title: "KPL Blue 7001 CkFV – Kesar Petroproducts Ltd. | Plastic Pigment",
                    description: "KPL Blue 7001 CkFV provides excellent color strength and heat stability (300°C) for PVC, Polyolefins, Nylon 6, PBT/PET, and PP Fiber applications.",
                    keywords: "KPL Blue 7001 CkFV, PB 15.1, Plastic Pigment, PVC, Polyolefins, Kesar Petroproducts",
                    author: "Kesar Petroproducts Ltd.",
                    robots: "index,follow",
                },
            },
            {
                slug: "kpl-blue-7003-k",
                name: "KPL Blue 7003 K",
                desc: "Good dispersion and color strength with heat stability of 260°C",
                tags: ["PB 15.3", "Plastic"],
                application: ["Polyolefins", "PVC & PVC Leather", "PA / ABS", "Nylon 6", "PBT / PET", "PP Fiber"],
                Properties: ["Light Fastness Full Tone / RT: 8/8", "Weather Fastness Full Tone / RT: 5/5", "Heat Stability in HDPE (°C): 260", "Bleeding in PVC - P: 4-5"],
                shades: ["#2C2681", "#3565B9"],
                msds: `/product/MSDS/3_MSDS Plastic All Grades/KPL Blue 7003 K.pdf`,
                tds: `/product/TDS/TDS KPL Blue 7003 K.pdf`,
                category: "Plastic",
                use: ["Suitable", "Potential use"],
                meta: {
                    title: "KPL Blue 7003 K – Kesar Petroproducts Ltd. | Plastic Pigment",
                    description: "KPL Blue 7003 K provides good dispersion, color strength, and heat stability (260°C) for a variety of plastic applications including PVC and Polyolefins.",
                    keywords: "KPL Blue 7003 K, PB 15.3, Plastic Pigment, PVC, Polyolefins, Kesar Petroproducts",
                    author: "Kesar Petroproducts Ltd.",
                    robots: "index,follow",
                },
            },
            {
                slug: "kpl-blue-7003-kfv",
                name: "KPL Blue 7003 KFV",
                desc: "Good dispersion and color strength with heat stability of 300°C and good FPV value",
                tags: ["PB 15.3", "Plastic"],
                application: ["Polyolefins", "PVC & PVC Leather", "PA / ABS", "Nylon 6", "PBT / PET", "PP Fiber"],
                Properties: ["Light Fastness Full Tone / RT: 8/8", "Weather Fastness Full Tone / RT: 5/5", "Heat Stability in HDPE (°C): 260", "Bleeding in PVC - P: 4-5"],
                shades: ["#2C2681", "#3565B9"],
                msds: `/product/MSDS/3_MSDS Plastic All Grades/KPL Blue 7003 K FV.pdf`,
                tds: `/product/TDS/TDS KPL Blue 7003 KFV.pdf`,
                category: "Plastic",
                use: ["Suitable", "Potential use"],
                meta: {
                    title: "KPL Blue 7003 KFV – Kesar Petroproducts Ltd. | Plastic Pigment",
                    description: "KPL Blue 7003 KFV offers excellent dispersion, color strength, and heat stability (300°C) for diverse plastic applications.",
                    keywords: "KPL Blue 7003 KFV, PB 15.3, Plastic Pigment, PVC, Polyolefins, Kesar Petroproducts",
                    author: "Kesar Petroproducts Ltd.",
                    robots: "index,follow",
                },
            },
            {
                slug: "kp-green-9000-k",
                name: "KP Green 9000 K",
                desc: "Good dispersion and color strength with moderate heat stability of 300°C",
                tags: ["PG 7", "Plastic"],
                application: ["Polyolefins", "PVC & PVC Leather", "PA / ABS", "Nylon 6", "PBT / PET", "PP Fiber"],
                Properties: ["Light Fastness Full Tone / RT: 8/8", "Weather Fastness Full Tone / RT: 5/5", "Heat Stability in HDPE (°C): 300", "Bleeding in PVC - P: 5"],
                shades: ["#00A02C", "#5BDE69"],
                msds: `/product/MSDS/3_MSDS Plastic All Grades/KPL Green 9000 K.pdf`,
                tds: `/product/TDS/TDS Plastic All Grades.xlsx`,
                category: "Plastic",
                use: ["Suitable", "Potential use"],
                meta: {
                    title: "KP Green 9000 K – Kesar Petroproducts Ltd. | Plastic Pigment",
                    description: "KP Green 9000 K provides good dispersion, color strength, and moderate heat stability (300°C), suitable for various plastic applications.",
                    keywords: "KP Green 9000 K, PG 7, Plastic Pigment, PVC, Polyolefins, Kesar Petroproducts",
                    author: "Kesar Petroproducts Ltd.",
                    robots: "index,follow",
                },
            },
        ]

    },
    {
        category: "Offset",
        products: [
            {
                slug: "kpl-blue-7000-u",
                name: "KPL Blue 7000 U",
                desc: "Cyan offset ink (widely used for shade adjustment by ink manufacturer)",
                tags: ["PB 15.0", "Offset"],
                application: ["Offset Ink"],
                shades: ["#18193C", "#4464BA"],
                msds: `/product/MSDS/4_MSDS Offset All Grades/MSDS KPL Blue 7000 U.pdf`,
                tds: `/product/TDS/TDS offset All Grades.xlsx`,
                category: "Offset",
                use: ["Suitable", "Potential use"],
                meta: {
                    title: "KPL Blue 7000 U – Kesar Petroproducts Ltd. | Offset Ink",
                    description: "KPL Blue 7000 U is a cyan offset ink widely used for shade adjustment by ink manufacturers, offering excellent dispersion and print quality.",
                    keywords: "KPL Blue 7000 U, PB 15.0, Offset Ink, Cyan Ink, Kesar Petroproducts",
                    author: "Kesar Petroproducts Ltd.",
                    robots: "index,follow",
                },
            },
            {
                slug: "kpl-blue-7003-og",
                name: "KPL Blue 7003 OG",
                desc: "Cyan for offset with greener shade and dispersion",
                tags: ["PB 15.3", "Offset"],
                application: ["Offset Ink"],
                shades: ["#3347AA", "#3565B9"],
                msds: `/product/MSDS/4_MSDS Offset All Grades/MSDS KPL Blue 7003 OG.pdf`,
                tds: `/product/TDS/TDS offset All Grades.xlsx`,
                category: "Offset",
                use: ["Suitable", "Potential use"],
                meta: {
                    title: "KPL Blue 7003 OG – Kesar Petroproducts Ltd. | Offset Ink",
                    description: "KPL Blue 7003 OG is a cyan offset ink with a greener shade and excellent dispersion for high-quality printing.",
                    keywords: "KPL Blue 7003 OG, PB 15.3, Offset Ink, Cyan Ink, Kesar Petroproducts",
                    author: "Kesar Petroproducts Ltd.",
                    robots: "index,follow",
                },
            },
            {
                slug: "kpl-blue-7003-or",
                name: "KPL Blue 7003 OR",
                desc: "Cyan for offset with redder shade and dispersion",
                tags: ["PB 15.3", "Offset"],
                application: ["Offset Ink"],
                shades: ["#2C2681", "#3565B9"],
                msds: `/product/MSDS/4_MSDS Offset All Grades/MSDS KPL Blue 7003 OR.pdf`,
                tds: `/product/TDS/TDS offset All Grades.xlsx`,
                category: "Offset",
                use: ["Suitable", "Potential use"],
                meta: {
                    title: "KPL Blue 7003 OR – Kesar Petroproducts Ltd. | Offset Ink",
                    description: "KPL Blue 7003 OR is a cyan offset ink with a redder shade and excellent dispersion for professional offset printing applications.",
                    keywords: "KPL Blue 7003 OR, PB 15.3, Offset Ink, Cyan Ink, Kesar Petroproducts",
                    author: "Kesar Petroproducts Ltd.",
                    robots: "index,follow",
                },
            },
            {
                slug: "kpl-blue-7003-ogf",
                name: "KPL Blue 7003 OGF",
                desc: "Greener cyan with excellent flow and printability",
                tags: ["PB 15.3", "Offset"],
                application: ["Offset Ink", "Metal Deco", "Screen Ink"],
                shades: ["#3347AA", "#3565B9"],
                msds: `/product/MSDS/4_MSDS Offset All Grades/MSDS KPL Blue 7003 OGF.pdf`,
                tds: `/product/TDS/TDS offset All Grades.xlsx`,
                category: "Offset",
                use: ["Suitable", "Potential use"],
                meta: {
                    title: "KPL Blue 7003 OGF – Kesar Petroproducts Ltd. | Offset Ink",
                    description: "KPL Blue 7003 OGF is a greener cyan ink for offset, metal deco, and screen printing with excellent flow and printability.",
                    keywords: "KPL Blue 7003 OGF, PB 15.3, Offset Ink, Cyan Ink, Screen Ink, Kesar Petroproducts",
                    author: "Kesar Petroproducts Ltd.",
                    robots: "index,follow",
                },
            },
            {
                slug: "kpl-blue-7003-orf",
                name: "KPL Blue 7003 ORF",
                desc: "Redder cyan with flow and excellent printability",
                tags: ["PB 15.3", "Offset"],
                application: ["Offset Ink", "Metal Deco", "Screen Ink", "Screen Ink"],
                shades: ["#2C2681", "#3565B9"],
                msds: `/product/MSDS/4_MSDS Offset All Grades/MSDS KPL Blue 7003 ORF.pdf`,
                tds: `/product/TDS/TDS offset All Grades.xlsx`,
                category: "Offset",
                use: ["Suitable", "Potential use"],
                meta: {
                    title: "KPL Blue 7003 ORF – Kesar Petroproducts Ltd. | Offset Ink",
                    description: "KPL Blue 7003 ORF is a redder cyan offset ink with excellent flow and printability, suitable for offset, metal deco, and screen printing.",
                    keywords: "KPL Blue 7003 ORF, PB 15.3, Offset Ink, Cyan Ink, Kesar Petroproducts",
                    author: "Kesar Petroproducts Ltd.",
                    robots: "index,follow",
                },
            },
            {
                slug: "kp-green-9000-u",
                name: "KP Green 9000 U",
                desc: "Green offset ink with good dispersion",
                tags: ["PG 7", "Offset"],
                application: ["Offset Ink"],
                shades: ["#00A02C", "#5BDE69"],
                msds: `/product/MSDS/4_MSDS Offset All Grades/MSDS KPL Green 9000 U.pdf`,
                tds: `/product/TDS/TDS offset All Grades.xlsx`,
                category: "Offset",
                use: ["Suitable", "Potential use"],
                meta: {
                    title: "KP Green 9000 U – Kesar Petroproducts Ltd. | Offset Ink",
                    description: "KP Green 9000 U is a green offset ink with good dispersion, suitable for various offset printing applications.",
                    keywords: "KP Green 9000 U, PG 7, Offset Ink, Green Ink, Kesar Petroproducts",
                    author: "Kesar Petroproducts Ltd.",
                    robots: "index,follow",
                },
            },
        ]
    },
    {
        category: "Anti Corrosives",
        products: [
            {
                slug: "zinc-phosphate",
                name: "Zinc Phosphate",
                desc: "(also known as Trizinc Phosphate, Trizinc Diphosphate, or Zinc Orthophosphate)",
                tags: ["Zn₃(PO₄)₂", "Anti Corrosives"],
                application: ["Corrosion-Resistant Coatings", "Dental Cement", "Industrial Applications", "Pigments"],
                shades: ["#FFFFFF"],
                style: "center",
                category: "Anti Corrosives",
                use: ["Suitable", "Potential use"],
                meta: {
                    title: "Zinc Phosphate – Kesar Petroproducts Ltd. | Anti Corrosive",
                    description: "Zinc Phosphate (Trizinc Phosphate, Trizinc Diphosphate, or Zinc Orthophosphate) is used in corrosion-resistant coatings, dental cement, industrial applications, and pigments.",
                    keywords: "Zinc Phosphate, Trizinc Phosphate, Anti Corrosives, Kesar Petroproducts, Corrosion-Resistant Coatings, Industrial Chemicals",
                    author: "Kesar Petroproducts Ltd.",
                    robots: "index,follow",
                },
            },
            {
                slug: "zinc-oxide",
                name: "Zinc Oxide",
                desc: "(used in ceramics)",
                tags: ["ZnO", "Anti Corrosives"],
                application: ["Cosmetics and Skincare", "Paints and Coatings", "Rubber Industry", "Ceramics and Glass", "Pharmaceuticals", "Electronics", "Agriculture"],
                shades: ["#FFFFFF"],
                style: "center",
                category: "Anti Corrosives",
                use: ["Suitable", "Potential use"],
                meta: {
                    title: "Zinc Oxide – Kesar Petroproducts Ltd. | Anti Corrosive",
                    description: "Zinc Oxide is used in ceramics, cosmetics, paints, rubber industry, pharmaceuticals, electronics, and agriculture, providing excellent corrosion resistance.",
                    keywords: "Zinc Oxide, ZnO, Anti Corrosives, Kesar Petroproducts, Ceramics, Cosmetics, Paints, Rubber Industry",
                    author: "Kesar Petroproducts Ltd.",
                    robots: "index,follow",
                },
            },
            {
                slug: "zinc-carbonate",
                name: "Zinc Carbonate",
                desc: "(used in ceramics)",
                tags: ["ZnCO₃", "Anti Corrosives"],
                application: ["Cosmetics and Skincare", "Rubber Industry", "Pharmaceuticals", "Pigments and Coatings", "Chemical Synthesis", "Agriculture"],
                shades: ["#FFFFFF"],
                style: "center",
                category: "Anti Corrosives",
                use: ["Suitable", "Potential use"],
                meta: {
                    title: "Zinc Carbonate – Kesar Petroproducts Ltd. | Anti Corrosive",
                    description: "Zinc Carbonate is used in ceramics, cosmetics, rubber, pharmaceuticals, pigments, chemical synthesis, and agriculture, offering reliable anti-corrosive properties.",
                    keywords: "Zinc Carbonate, ZnCO₃, Anti Corrosives, Kesar Petroproducts, Ceramics, Cosmetics, Pigments, Chemical Synthesis",
                    author: "Kesar Petroproducts Ltd.",
                    robots: "index,follow",
                },
            },
        ]
    },
    {
        category: "Fertilizers",
        products: [
            {
                slug: "diammonium-phosphate",
                name: "Diammonium Phosphate",
                desc: "(also known as Diammonium Hydrogen Phosphate or Ammonium Phosphate Dibasic)",
                tags: ["(NH₄)₂HPO₄ ", "Fertilizers"],
                application: ["Fertilizers", "Fire Retardants", "Food Industry", "Industrial Applications", "Chemical Synthesis"],
                shades: ["#FFFFFF"],
                style: "center",
                category: "Fertilizers",
                use: ["Suitable", "Potential use"],
                meta: {
                    title: "Diammonium Phosphate – Kesar Petroproducts Ltd. | Fertilizers",
                    description: "Diammonium Phosphate (DAP) is used in fertilizers, fire retardants, food industry, industrial applications, and chemical synthesis, providing essential nutrients for crops.",
                    keywords: "Diammonium Phosphate, DAP, Fertilizers, Kesar Petroproducts, Industrial Chemicals, Agriculture, Fire Retardants",
                    author: "Kesar Petroproducts Ltd.",
                    robots: "index,follow",
                },
            },
            {
                slug: "mono-ammonium-phosphate",
                name: "Mono Ammonium Phosphate",
                desc: "(also known as Ammonium Dihydrogen Phosphate or Ammonium Phosphate Monobasic)",
                tags: ["NH₄H₂PO₄", "Fertilizers"],
                application: ["Fertilizers", "Fire Retardants", "Food Industry", "Industrial Applications", "Analytical Chemistry"],
                shades: ["#FFFFFF"],
                style: "center",
                category: "Fertilizers",
                use: ["Suitable", "Potential use"],
                meta: {
                    title: "Mono Ammonium Phosphate – Kesar Petroproducts Ltd. | Fertilizers",
                    description: "Mono Ammonium Phosphate (MAP) is widely used in fertilizers, fire retardants, food industry, industrial applications, and analytical chemistry for nutrient-rich formulations.",
                    keywords: "Mono Ammonium Phosphate, MAP, Fertilizers, Kesar Petroproducts, Agriculture, Fire Retardants, Industrial Chemicals",
                    author: "Kesar Petroproducts Ltd.",
                    robots: "index,follow",
                },
            },
            {
                slug: "zinc-sulphate",
                name: "Zinc Sulphate",
                desc: "(also known as Zinc Sulfate)",
                tags: ["ZnSO₄", "Fertilizers"],
                application: ["Agriculture", "Animal Feed", "Pharmaceuticals", "Industrial Applications", "Water Treatment", "Chemical Synthesis"],
                shades: ["#FFFFFF"],
                style: "center",
                category: "Fertilizers",
                use: ["Suitable", "Potential use"],
                meta: {
                    title: "Zinc Sulphate – Kesar Petroproducts Ltd. | Fertilizers",
                    description: "Zinc Sulphate (ZnSO₄) is used in agriculture, animal feed, pharmaceuticals, industrial applications, water treatment, and chemical synthesis, providing essential zinc nutrients.",
                    keywords: "Zinc Sulphate, ZnSO₄, Fertilizers, Kesar Petroproducts, Agriculture, Pharmaceuticals, Industrial Chemicals, Water Treatment",
                    author: "Kesar Petroproducts Ltd.",
                    robots: "index,follow",
                },
            },
        ]
    }
];
